---
title: |
  | The Europen Public-Firm Audit Market: 
  | Some exploratory insights  \vspace{1cm}

author: |
  | Joachim Gassen 
  | TRR 266 Accounting for Transparency
  | Humboldt-Universität zu Berlin 
  | gassen@wiwi.hu-berlin.de

date: |
  | `r loc <- Sys.getlocale(category = "LC_TIME"); Sys.setlocale("LC_TIME", "C"); fdate <- format(Sys.time(), '%B %e, %Y'); Sys.setlocale("LC_TIME", loc); fdate` \vspace{1cm}
  
abstract: |
  | Building on sample of European publicly-listed clients and their audit fees I explore the market share of Big 4 auditing firm across time, countries and idustries. I further assess the audit fee differential between Big 4 and non Big 4 firms. 
  | \vspace{6cm}

output:
  pdf_document: 
    number_sections: true
  toc: no
fig_caption: yes
fontsize: 11pt
ident: yes

always_allow_html: yes

header-includes:
  - \usepackage[nomarkers,nolists]{endfloat}    
  - \usepackage{setspace}\doublespacing
  - \setlength{\parindent}{4em}
  - \setlength{\parskip}{0em}
  - \usepackage[hang,flushmargin]{footmisc}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=24pt,font=bf}
  - \usepackage{array}
  - \usepackage{threeparttable}
  - \usepackage{adjustbox}
  - \usepackage{graphicx}
  - \usepackage{csquotes}
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(lubridate)
library(knitr)
library(ExPanDaR)
library(kableExtra)
opts_chunk$set(fig.pos = 'p') # Places figures on their own pages
opts_chunk$set(out.width = '100%', dpi=300)
opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, cache = TRUE)
options(ggplot2.discrete.color = c("blue", "#af01ef"), ggplot2.discrete.fill = c("blue", "#af01ef"))
```

```{r prepData, include=FALSE}
afees_eu <- readRDS("../data/generated/afees_eu.rds")
ff12 <- read_csv(
  "../data/external/fama_french_12_industries.csv", col_types = cols()
)

afees_eu_desc <- afees_eu %>%
  group_by(entity_map_fkey, isin, entity_name, audit_fee_fiscal_year_end) %>%
  arrange(entity_map_fkey, isin, entity_name, audit_fee_fiscal_year_end) %>%
  summarise(
    year = unique(year(audit_fee_fiscal_year_end)),
    sic = unique(sic_code_fkey),
    hq_iso2c = unique(headquarter_country_code), 
    big4 = any(1:4 %in% auditor_fkey),
    audit_fees_eur = sum(audit_fees_eur),
    total_non_audit_fees_eur = sum(total_non_audit_fees_eur), 
    total_fees_eur = sum(total_fees_eur), 
    market_cap_eur = mean(market_cap_eur, na.rm = TRUE), 
    revenues_eur = mean(revenue_eur, na.rm = TRUE),
    assets_eur = mean(assets_eur, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  group_by(entity_map_fkey) %>%
  filter(
    is.na(lag(audit_fee_fiscal_year_end)) | 
      ((month(audit_fee_fiscal_year_end) == 
        month(lag(audit_fee_fiscal_year_end))) &
          (day(audit_fee_fiscal_year_end) == 
             day(lag(audit_fee_fiscal_year_end))))
  ) %>%
  select(-audit_fee_fiscal_year_end) 

dups <- afees_eu_desc %>%
  group_by(entity_map_fkey, year) %>%
  filter(n() > 1)

if (nrow(dups) > 0) stop(
  "Audit fee descriptive data has duplicates. This should not happen"
)

afees_eu_clean <- afees_eu_desc %>%
  ungroup() %>%
  filter(year > 2008, year < 2021) %>%
  mutate(
    ltotal_fees = log((1 + total_fees_eur)),
    laudit_fees = log((1 + audit_fees_eur)),
    lnaudit_fees = log((1 + total_non_audit_fees_eur)),
    lassets = log(assets_eur),
    lrevenues = log(revenues_eur),
    lmarket_cap = log(market_cap_eur),
    tfees_ta = total_fees_eur/assets_eur
  ) %>%
  left_join(ff12, by = "sic") %>%
  filter(
    assets_eur > 0, revenues_eur > 0, market_cap_eur > 0,
    total_fees_eur > 0, audit_fees_eur > 0, !is.na(ff12_ind)
  )  %>%
  select(
    entity_map_fkey, isin, entity_name, hq_iso2c, ff12_ind, year, lassets, lrevenues, 
    lmarket_cap, big4, laudit_fees, lnaudit_fees, ltotal_fees
  ) %>% group_by(hq_iso2c) %>% filter(n() >= 1000) %>% ungroup()

```

```{r YearBar, echo = FALSE, fig.align="center", fig.cap="\\label{fig:YearBar}Number of Clients by Year"}

ggplot(afees_eu_clean, aes(x = year, fill = big4)) +
  geom_bar() + 
  labs(x = "", y = "Fiscal Year", fill = "Auditor") +
  scale_fill_discrete(labels = c("Non Big 4", "Big 4")) +
  theme_minimal() + theme(
    legend.position = "bottom"
  )
  
```

```{r CountryBar, echo = FALSE, fig.align="center", fig.cap="\\label{fig:CountryBar}Number of Clients by Country"}

df <- afees_eu_clean %>% mutate(
  country = countrycode::countrycode(
    hq_iso2c, origin = "iso2c", destination = "country.name" 
  )
)
  
ggplot(df, aes(x = country, fill = big4)) +
  geom_bar() + 
  labs(x = "", y = "Number of Clients", fill = "Auditor") +
  scale_fill_discrete(labels = c("Non Big 4", "Big 4")) +
  theme_minimal() + theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
    legend.position = "bottom"
  )
  
```

```{r IndustryBar, echo = FALSE, fig.align="center", fig.cap="\\label{fig:IndustryBar}Number of Clients by Industry"}

ggplot(afees_eu_clean, aes(x = ff12_ind, fill = big4)) +
  geom_bar() + 
  labs(x = "", y = "Number of Clients", fill = "Auditor") +
  scale_fill_discrete(labels = c("Non Big 4", "Big 4")) +
  coord_flip() + 
  theme_minimal() + theme(
    legend.position = "bottom"
  )
  
```


```{r ClientMSAbsolute, echo = FALSE, fig.align="center", fig.cap="\\label{fig:Big4MSFeesOverTime}Absolute Client Market Shares Over Time"}

mshares_year <- afees_eu_clean %>%
  group_by(year, big4) %>%
  summarise(
    sum_fees = sum(exp(laudit_fees) - 1)/1e6,
    clients = n(),
    .groups = "drop_last"
  ) %>% mutate(
    sum_fees_p = sum_fees / sum(sum_fees),
    clients_p = clients / sum(clients),
  )

ggplot(mshares_year, aes(x = year, y = clients, fill = big4)) +
  geom_area() + 
  labs(x = "Fiscal Year", y = "Number of Clients", fill = "Auditor") +
  scale_fill_discrete(labels = c("Non Big 4", "Big 4")) +
  theme_minimal() + theme(legend.position = "bottom")
```


```{r ClientMSRelative, echo = FALSE, fig.align="center", fig.cap="\\label{fig:Big4MSFeesOverTime}Realtive Client Market Share Over Time"}

ggplot(mshares_year, aes(x = year, y = clients_p, fill = big4)) +
  geom_area() + 
  labs(x = "Fiscal Year", y = "Client Market Share [%]", fill = "Auditor") +
  scale_fill_discrete(labels = c("Non Big 4", "Big 4")) +
  theme_minimal() + theme(legend.position = "bottom")
  
```

```{r FeeMSAbsolute, echo = FALSE, fig.align="center", fig.cap="\\label{fig:Big4MSFeesOverTime}Absolute Fee Market Share Over Time"}

ggplot(mshares_year, aes(x = year, y = sum_fees, fill = big4)) +
  geom_area() + 
  labs(x = "Fiscal Year", y = "Total Audit Fees [Mio. Euro]", fill = "Auditor") +
  scale_fill_discrete(labels =  c("Non Big 4", "Big 4")) +
  scale_y_continuous(labels = scales::label_percent()) +
  theme_minimal() + theme(legend.position = "bottom")
  
```

```{r FeeMSRelative, echo = FALSE, fig.align="center", fig.cap="\\label{fig:Big4MSFeesOverTime}Realtive Fee Market Share of Big 4 Firms Over Time"}

ggplot(mshares_year, aes(x = year, y = sum_fees_p, fill = big4)) +
  geom_area() + 
  labs(x = "Fiscal Year", y = "Fee Market Share [%]", fill = "Auditor") +
  scale_fill_discrete(labels = c("Non Big 4", "Big 4")) +
  scale_y_continuous(labels = scales::label_percent()) +
  theme_minimal() + theme(legend.position = "bottom")
  
```

```{r BoxPlot, echo = FALSE, fig.align="center", fig.cap="\\label{fig:Scatter}Audit Fees by Audit Type"}

df <- afees_eu_clean %>%
  mutate(
    assets = exp(lassets),
    audit_fees = (exp(laudit_fees) - 1)
  )

ggplot(df, aes(x = big4, y = audit_fees, color = big4)) +
  geom_boxplot() + 
  labs(x = "", y = "Audit Fees [Euro]", fill = "Auditor") +
  scale_x_discrete(labels = c("Non Big 4", "Big 4")) +
  scale_y_log10(labels = scales::label_comma()) +
  theme_minimal() + theme(legend.position = "none")
  
```


```{r Scatter, echo = FALSE, fig.align="center", fig.cap="\\label{fig:Scatter}Audit Fees by Firm Size"}

ggplot(df, aes(x = assets, y = audit_fees, color = big4)) +
  geom_point(alpha = 0.1) + 
  labs(x = "Total Assets [Euro]", y = "Audit Fees [Euro]", fill = "Auditor") +
  scale_color_discrete(labels = c("Non Big 4", "Big 4")) +
  scale_x_log10(labels = scales::label_comma()) +
  scale_y_log10(labels = scales::label_comma()) +
  theme_minimal() + theme(legend.position = "bottom")
  
```


```{r Desc, echo = FALSE, results = "asis"}

var_labels <- c(
  "Audit fees", "Assets", "Sales", "Market Capitalization", "Big 4"
)
desc_rnames <- paste0("\\textit{", var_labels, "}")

df <- afees_eu_clean %>%
  mutate(
    entity_map_fkey = as.factor(entity_map_fkey),
    audit_fees = (exp(laudit_fees) - 1)/1e6,
    assets = exp(lassets)/1e6,
    revenues = exp(lrevenues)/1e6,
    market_cap = exp(lmarket_cap)/1e6,
  ) %>%
  select(
    hq_iso2c, entity_map_fkey, entity_name, year, ff12_ind, 
    audit_fees, assets, revenues, market_cap, big4,
    laudit_fees, lassets, lrevenues, lmarket_cap
  )

desc_df <- df %>% select(-starts_with("l"))  
t <- prepare_descriptive_table(desc_df %>% select(-year))
rownames(t$df) <- desc_rnames
names(t$df)[c(5,7)] <- c("25 \\%", "75 \\%")
kable(t$df, digits = c(0, 3, 3, 3, 3, 3, 3, 3), format = "latex",
      caption = "\\label{tab:descriptives}Descriptive Statistics",
      format.args = list(decimal.mark = ".", big.mark = ",", 
                         scientific=FALSE),
      booktabs = TRUE, escape = FALSE, linesep = "") -> kab_latex

lat_tab <- unlist(strsplit(kab_latex, "\n"))
lat_tab[6] <- "\\\\[-1.8ex]\\hline \\hline \\\\[-1.8ex]"
lat_tab[8] <- "\\hline\\\\[-1.8ex]"
lat_tab[length(lat_tab) - 2] <- "\\\\[-1.8ex]\\hline \\hline \\\\[-1.8ex]"

latex_tab <- c(
  "\\begin{table}[!htbp]",  
  lat_tab[3],
  "\\begin{adjustbox}{width=\\textwidth}",
  "\\begin{threeparttable}",
  lat_tab[5:(length(lat_tab) - 1)],
  "\\begin{tablenotes}[flushleft]",
  "\\setlength{\\labelsep}{0pt}",
  "\\footnotetext",
  sprintf(
    paste(
      "\\item Note: The data is obtained from the Audit Analytics as provided",
      "by WRDS. The sample covers the period %d to %d and %s unique clients",
      "form %d countries. Countries with less tham 1,000 observations are excluded.",
      "For audits involving multiple audit firms, audit fees are aggregated",
      "at the client-fiscal year level so that Audit fees represents the audit",
      "fees that the client incurred during a fiscal year. Assets and market",
      "capitalization are measured at the fiscal year end. Revenues reresent",
      "net sales during the fiscal year.", 
      "All values are measured in Mio. Euro. Big 4 is a binary variable",
      "taking the value of one whenever a Big 4 auditing firm (KPMG, PWC,",
      "EY or Deloitte) is involved in the audit."
    ),
    min(desc_df$year), max(desc_df$year), 
    format(length(unique(desc_df$entity_map_fkey)), big.mark = ","),
    length(unique(desc_df$hq_iso2c))
  ),
  "\\end{tablenotes}",
  "\\end{threeparttable}",
  "\\end{adjustbox}",
  "\\end{table}"
)
cat(paste(latex_tab, collapse = "\n"))  
```


``` {r CorrTable, results="asis"}
var_labels <- c(
  "Ln(Audit fees)", "Ln(Assets)", "Ln(Revenues)", "Ln(Market Capitalization)", 
  "Big 4"
)
var_names <- c("laudit_fees", "lassets", "lrevenues", "lmarket_cap", "big4")
tab <- prepare_correlation_table(
  df %>% select(all_of(var_names)), format = "latex", booktabs = T
)
lat_tab <- unlist(strsplit(tab$kable_ret, "\n"))
lat_tab[7:(6 + length(var_names))] <- str_replace(
  lat_tab[7:(6 + length(var_names))], fixed(var_names), var_labels
)
lat_tab[4] <- "\\\\[-0.9ex]\\hline \\hline \\\\[-0.9ex]"
lat_tab[6] <- "\\hline\\\\[-1.8ex]"
lat_tab[(7 + length(var_names))] <- "\\\\[-0.9ex]\\hline \\hline \\\\[-0.9ex]"
lat_tab[(9 + length(var_names))] <- "\\begin{tablenotes}[flushleft]"
lat_tab[(10 + length(var_names))] <- sprintf(
  paste(
    "\\item This table reports Pearson correlations above and Spearman", 
    "correlations below the diagonal. Number of observations: %s.", 
    "Correlations with significance levels below 5\\%% appear in bold print."
  ), format(nrow(df), big.mark = ",")
)
latex_tab <- c(
  "\\begin{table}[!htbp]",  
  "\\centering",
  "\\caption{\\label{tab:corr}Correlations}",
  lat_tab,
  "\\end{table}"
)
cat(paste(latex_tab, collapse = "\n"))
```

``` {r RegTable, results="asis"}
tab <- prepare_regression_table(
  df, rep("laudit_fees", 4), 
  idvs = list(
    c("big4", "lassets"),  
    c("big4", "lassets", "lrevenues", "lmarket_cap"),  
    c("big4", "lassets"),  
    c("big4", "lassets", "lrevenues", "lmarket_cap")
  ),
  feffects = list("", "", c("entity_map_fkey", "year"), c("entity_map_fkey", "year")),
  clusters = list("", "", c("entity_map_fkey", "year"), c("entity_map_fkey", "year")),
  format = "latex"
)$table

tab[10] <- paste(
  " & \\multicolumn{4}{c}{\\textit{Dependent variable: ", var_labels[1], "}} \\\\"
)
esc_var_names <- str_replace_all(var_names, fixed ("_"), "\\_")
reg_names <- tibble(
  var_name = esc_var_names[c(5, 2:4)],
  label = var_labels[c(5, 2:4)]
)
for (i in seq(15, 24, by = 3)) {
  pos <- (i-12)/3
  tab[i] <- str_replace(
    tab[i], fixed(reg_names$var_name[pos]), reg_names$label[pos]
  )
}

tab[32:33] <- str_replace_all(tab[32:33], fixed("entity\\_map\\_fkey"), "Client")
tab[32:33] <- str_replace_all(tab[32:33], fixed("year"), "Year")
tab <- tab[c(8, 11, 12:36, 38)]

latex_tab <- c(
  "\\begin{table}[!htbp]",  
  "\\caption{\\label{tab:reg}Regressions}",
  "\\centering",
  "\\begin{threeparttable}",
  "\\begin{tabular}{lcccc}",
  tab,
  "\\end{tabular}",
  "\\begin{tablenotes}[flushleft]",
  "\\item",
  "This table presents the results of four OLS regressions.", 
  "Sample and all variables are as defined in Table 1.",
  "Standard errors are presented in parentheses below the coefficients.",
  "$^{*}$/$^{**}$/$^{***}$ indicate two-sided significance levels below",
  "10/5/1 \\%, respectively.",
  "\\end{tablenotes}",
  "\\end{threeparttable}",
  "\\end{table}"
)
cat(paste(latex_tab, collapse = "\n"))
```

\pagebreak

\setcounter{table}{0}
\renewcommand{\thetable}{\arabic{table}}

