---
title: |
  | The European Public-Firm Audit Market: 
  | Some exploratory insights  \vspace{1cm}

author: |
  | Joachim Gassen 
  | TRR 266 Accounting for Transparency
  | Humboldt-Universität zu Berlin 
  | gassen@wiwi.hu-berlin.de

date: |
  | `r loc <- Sys.getlocale(category = "LC_TIME"); Sys.setlocale("LC_TIME", "C"); fdate <- format(Sys.time(), '%B %e, %Y'); Sys.setlocale("LC_TIME", loc); fdate` \vspace{1cm}
  
abstract: |
  | Building on a sample of European publicly-listed clients and their audit fees I explore the market share of Big 4 auditing firm across time, countries and industries. I further assess the audit fee premium of Big 4 Auditing firms. 
  | \vspace{6cm}

output:
  pdf_document: 
    number_sections: true
  toc: no
fig_caption: yes
fontsize: 11pt
ident: yes

always_allow_html: yes

header-includes:
  - \usepackage{setspace}\doublespacing
  - \setlength{\parindent}{4em}
  - \setlength{\parskip}{0em}
  - \usepackage[hang,flushmargin]{footmisc}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=24pt,font=bf}
  - \captionsetup[figure]{skip=24pt,font=bf}
  - \usepackage{floatrow}
  - \floatsetup[figure]{capposition=top}
  - \floatsetup[table]{capposition=top}
  - \usepackage{array}
  - \usepackage{threeparttable}
  - \usepackage{adjustbox}
  - \usepackage{graphicx}
  - \usepackage{csquotes}
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
suppressMessages({
  library(tidyverse)
  library(lubridate)
  library(knitr)
  library(ExPanDaR)
  library(kableExtra)
  library(modelsummary)
})

message("Preparing EDA PDF... ", appendLF = FALSE)

opts_chunk$set(fig.pos = 'p') # Places figures on their own pages
opts_chunk$set(out.width = '100%', dpi=300)
opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
options(
  ggplot2.discrete.colour = RColorBrewer::brewer.pal(8, "Set1"), 
  ggplot2.discrete.fill = RColorBrewer::brewer.pal(8, "Set1")
)
options("modelsummary_format_numeric_latex" = "plain")

toprule <- "\\toprule"
midrule <- "\\midrule"
bottomrule <- "\\bottomrule"

afees_eu_clean <- readRDS("../data/generated/afees_eu_clean.rds")
```


```{r Desc, echo = FALSE, results = "asis"}

var_labels <- c(
  "Audit fees", "Assets", "Revenues", "Market Capitalization", "Big 4"
)
desc_rnames <- paste0("\\textit{", var_labels, "}")

smp <- afees_eu_clean %>%
  select(
    hq_iso2c, entity_map_fkey, entity_name, year, ff12_ind, 
    audit_fees, assets, revenues, market_cap, big4,
    laudit_fees, lassets, lrevenues, lmarket_cap
  )

smp_desc <- smp %>% select(-starts_with("l"))  
t <- prepare_descriptive_table(smp_desc %>% select(-year))
rownames(t$df) <- desc_rnames
names(t$df)[c(5,7)] <- c("25 \\%", "75 \\%")
kable(t$df, digits = c(0, 3, 3, 3, 3, 3, 3, 3), format = "latex",
      caption = "\\label{tab:descriptives}Descriptive Statistics",
      format.args = list(decimal.mark = ".", big.mark = ",", 
                         scientific=FALSE),
      booktabs = TRUE, escape = FALSE, linesep = "") -> kab_latex

lat_tab <- unlist(strsplit(kab_latex, "\n"))
lat_tab[6] <- "\\hline\\\\[-1.8ex]"  # toprule 

# For whatever reason, toprule gives an error 
# "! Package graphics Error: Division by 0."
# when used with adjustbox

lat_tab[8] <-  midrule # "\\hline\\\\[-1.8ex]"
lat_tab[length(lat_tab) - 2] <- bottomrule # bottomrule

latex_tab <- c(
  "\\begin{table}[!htbp]",  
  "\\begin{adjustbox}{width=\\textwidth}",
  lat_tab[3],
  "\\begin{threeparttable}",
  lat_tab[5:(length(lat_tab) - 1)],
  "\\begin{tablenotes}[flushleft]",
  "\\setlength{\\labelsep}{0pt}",
  "\\footnotetext",
  sprintf(
    paste(
      "\\item Notes: The data is obtained from Audit Analytics EU as provided",
      "by WRDS. The sample covers the periods %d to %d and %s unique clients",
      "form %d countries. Countries with less than 1,000 client-fiscal year", 
      "observations are excluded. For audits involving multiple audit firms", 
      "audit fees are aggregated at the client-fiscal year level so that",
      "\\textit{Audit fees} represents the audit fees that the client incurred", 
      "during a fiscal year. \\textit{Assets} and \\textit{Market",
      "Capitalization} are client values and measured at the fiscal year end.", 
      "\\textit{Revenues} reresents client net sales during the fiscal year.", 
      "All values are measured in Mio. Euro. \\textit{Big 4} is a binary", 
      "variable taking the value of one whenever a Big 4 auditing firm", 
      "(KPMG, PWC, EY or Deloitte) is involved in the audit."
    ),
    min(afees_eu_clean$year), max(afees_eu_clean$year), 
    format(length(unique(afees_eu_clean$entity_map_fkey)), big.mark = ","),
    length(unique(afees_eu_clean$hq_iso2c))
  ),
  "\\end{tablenotes}",
  "\\end{threeparttable}",
  "\\end{adjustbox}",
  "\\end{table}"
)
cat(paste(latex_tab, collapse = "\n"))  
```

```{r DescByGroup, echo = FALSE, results = "asis"}
smpd <- afees_eu_clean %>%
  mutate(auditor = ifelse(
    big4, 
    sprintf("Big 4 (n = %s)", format(sum(afees_eu_clean$big4), big.mark = ",")),
    sprintf("Non Big 4 (n = %s)", format(sum(!afees_eu_clean$big4), big.mark = ","))
  )) %>%
  select(
    auditor, audit_fees, assets, revenues, market_cap, 
    laudit_fees, lassets, lrevenues, lmarket_cap
  ) %>%
  as.data.frame()

var_labels <- c(
  "Auditor", "Audit fees",  
  "Assets", "Revenues", "Market Capitalization", 
  "Log(Audit fees)", "Log(Assets)", "Log(Revenues)", 
  "Log(Market Capitalization)"
)

desc_rnames <- paste0("\\textit{", var_labels, "}")

notes_tab <- sprintf(
  paste(
    "Notes: The data is obtained from Audit Analytics EU as provided",
    "by WRDS. The sample covers the periods %d to %d and %s unique clients",
    "form %d countries. Countries with less than 1,000 client-fiscal year", 
    "observations are excluded. For audits involving multiple audit firms", 
    "audit fees are aggregated at the client-fiscal year level so that",
    "\\\\textit{Audit fees} represents the audit fees that the client incurred", 
    "during a fiscal year. \\\\textit{Assets} and \\\\textit{Market",
    "Capitalization} are client values and measured at the fiscal year end.", 
    "\\\\textit{Revenues} reresents client net sales during the fiscal year.", 
    "All values are measured in Mio. Euro. \\\\textit{Big 4} is a binary", 
    "variable taking the value of one whenever a Big 4 auditing firm", 
    "(KPMG, PWC, EY or Deloitte) is involved in the audit."
  ),
  min(afees_eu_clean$year), max(afees_eu_clean$year), 
  format(length(unique(afees_eu_clean$entity_map_fkey)), big.mark = ","),
  length(unique(afees_eu_clean$hq_iso2c))
)

names(smpd) <- var_labels
datasummary(
  All(smpd)~Auditor*(Mean + SD + Median), data = smpd,
  title = "Descriptive Statistics by Auditor Type",
  fmt = function(x) format(round(x, 3), big.mark = ","),
  output = "latex",
  dinm = FALSE
) %>%
  footnote(
    general = notes_tab, footnote_as_chunk = TRUE, general_title = "",
    threeparttable = TRUE, escape = F
  ) 
```


```{r YearBar, echo = FALSE, fig.align="center", fig.cap="\\label{fig::YearBar}Number of Clients by Year"}

ggplot(afees_eu_clean, aes(x = year, fill = big4)) +
  geom_bar() + 
  labs(x = "", y = "Number of Clients", fill = "Auditor") +
  scale_y_continuous(labels = scales::label_comma()) +
  scale_fill_discrete(labels = c("Non Big 4", "Big 4")) +
  theme_minimal() + theme(
    legend.position = "bottom",
    text = element_text(family = "serif")
  )
  
```

```{r CountryBar, echo = FALSE, fig.align="center", fig.cap="\\label{fig::CountryBar}Number of Client Years by Country"}

df <- afees_eu_clean %>% mutate(
  country = countrycode::countrycode(
    hq_iso2c, origin = "iso2c", destination = "country.name" 
  )
)
  
ggplot(df, aes(x = country, fill = big4)) +
  geom_bar() + 
  labs(x = "", y = "Number of Client Years", fill = "Auditor") +
  scale_fill_discrete(labels = c("Non Big 4", "Big 4")) +
  scale_y_continuous(labels = scales::label_comma()) +
  theme_minimal() + theme(
    text = element_text(family = "serif"),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
    legend.position = "bottom"
  )
  
```

```{r IndustryBar, echo = FALSE, fig.align="center", fig.cap="\\label{fig::IndustryBar}Number of Client Years by Industry"}

ggplot(afees_eu_clean, aes(x = ff12_ind, fill = big4)) +
  geom_bar() + 
  labs(x = "", y = "Number of Client Years", fill = "Auditor") +
  scale_fill_discrete(labels = c("Non Big 4", "Big 4")) +
  scale_y_continuous(labels = scales::label_comma()) +
  coord_flip() + 
  theme_minimal() + theme(
    text = element_text(family = "serif"),
    legend.position = "bottom"
  )
  
```



```{r ClientMSRelative, echo = FALSE, fig.align="center", fig.cap="\\label{fig::ClientMSRelative}Relative Client Market Share Over Time"}
mshares_year <- afees_eu_clean %>%
  group_by(year, big4) %>%
  summarise(
    sum_fees = sum(exp(laudit_fees) - 1)/1e6,
    clients = n(),
    .groups = "drop_last"
  ) %>% mutate(
    sum_fees_p = sum_fees / sum(sum_fees),
    clients_p = clients / sum(clients),
  )

ggplot(mshares_year, aes(x = year, y = clients_p, fill = big4)) +
  geom_area() + 
  labs(x = "Fiscal Year", y = "Client Market Share [%]", fill = "Auditor") +
  scale_y_continuous(labels = scales::label_percent()) +
  scale_fill_discrete(labels = c("Non Big 4", "Big 4")) +
  theme_minimal() + theme(
    text = element_text(family = "serif"),
    legend.position = "bottom"
  )
  
```

```{r FeeMSAbsolute, echo = FALSE, fig.align="center", fig.cap="\\label{fig::FeeMSAbsolute}Absolute Fee Market Share Over Time"}

ggplot(mshares_year, aes(x = year, y = sum_fees, fill = big4)) +
  geom_area() + 
  labs(x = "Fiscal Year", y = "Total Audit Fees [Mio. Euro]", fill = "Auditor") +
  scale_fill_discrete(labels =  c("Non Big 4", "Big 4")) +
  scale_y_continuous(labels = scales::label_comma()) +
  theme_minimal() + 
  theme(
    text = element_text(family = "serif"),
    legend.position = "bottom"
  )
```

```{r FeeMSRelative, echo = FALSE, fig.align="center", fig.cap="\\label{fig::FeeMSRelative}Relative Fee Market Share Over Time"}

ggplot(mshares_year, aes(x = year, y = sum_fees_p, fill = big4)) +
  geom_area() + 
  labs(x = "Fiscal Year", y = "Fee Market Share [%]", fill = "Auditor") +
  scale_fill_discrete(labels = c("Non Big 4", "Big 4")) +
  scale_y_continuous(labels = scales::label_percent()) +
  theme_minimal() + 
  theme(
    text = element_text(family = "serif"),
    legend.position = "bottom"
  )
  
```

```{r BoxPlot, echo = FALSE, fig.align="center", fig.cap="\\label{fig::BoxPlot}Audit Fees by Auditor Type"}

df <- afees_eu_clean %>%
  mutate(
    assets = exp(lassets),
    audit_fees = (exp(laudit_fees) - 1)
  )

ggplot(df, aes(x = big4, y = audit_fees, color = big4, fill = big4)) +
  geom_boxplot(fill = NA, width = 0.15) + 
  geom_violin(alpha = 0.1, color = NA) +
  labs(x = "", y = "Audit Fee [Euro]", fill = "Auditor") +
  scale_x_discrete(labels = c("Non Big 4", "Big 4")) +
  scale_y_log10(labels = scales::label_comma()) +
  theme_minimal() + 
  theme(
    text = element_text(family = "serif"),
    legend.position = "none"
  )
  
```


```{r Scatter, echo = FALSE, fig.align="center", fig.cap="\\label{fig::Scatter}Audit Fees by Firm Size"}

ggplot(df, aes(x = assets, y = audit_fees, color = big4)) +
  geom_point(alpha = 0.1) + 
  labs(x = "Total Assets [Euro]", y = "Audit Fee [Euro]", color = "Auditor") +
  scale_color_discrete(labels = c("Non Big 4", "Big 4")) +
  scale_x_log10(labels = scales::label_comma()) +
  scale_y_log10(labels = scales::label_comma()) +
  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  theme_minimal() + theme(
    text = element_text(family = "serif"),
    legend.position = "bottom"
  )

```

```{r ContourPlot, echo = FALSE, fig.align="center", fig.cap="\\label{fig::ContourPlot}Audit Fees by Firm Size"}

ggplot(df, aes(x = assets, y = audit_fees, color = big4)) +
  geom_point(alpha = 0.01) + 
  stat_density_2d(size = 0.4, bins = 10) +
  labs(x = "Total Assets [Euro]", y = "Audit Fee [Euro]", color = "Auditor") +
  scale_color_discrete(labels = c("Non Big 4", "Big 4")) +
  scale_x_log10(labels = scales::label_comma()) +
  scale_y_log10(labels = scales::label_comma()) +
  guides(colour = guide_legend(override.aes = list(alpha = 1))) +
  theme_minimal() + theme(
    text = element_text(family = "serif"),
    legend.position = "bottom"
  )
```

``` {r CorrTable, results="asis"}
var_labels <- c(
  "Ln(Audit fees)", "Ln(Assets)", "Ln(Revenues)", "Ln(Market Capitalization)", 
  "Big 4"
)
var_names <- c("laudit_fees", "lassets", "lrevenues", "lmarket_cap", "big4")
tab <- prepare_correlation_table(
  smp %>% select(all_of(var_names)), format = "latex", booktabs = T
)
lat_tab <- unlist(strsplit(tab$kable_ret, "\n"))
lat_tab[7:(6 + length(var_names))] <- str_replace(
  lat_tab[7:(6 + length(var_names))], fixed(var_names), var_labels
)
lat_tab[4] <- toprule
lat_tab[6] <- "\\hline\\\\[-1.8ex]"
lat_tab[(7 + length(var_names))] <- bottomrule
lat_tab[(9 + length(var_names))] <- "\\begin{tablenotes}[flushleft]"
lat_tab[(10 + length(var_names))] <- sprintf(
  paste(
    "\\item Notes: This table reports Pearson correlations above and Spearman", 
    "correlations below the diagonal. Number of observations: %s.", 
    "Correlations with significance levels below 5\\%% appear in bold print."
  ), format(nrow(smp), big.mark = ",")
)
latex_tab <- c(
  "\\begin{table}[t]",  
  "\\centering",
  "\\caption{\\label{tab:corr}Correlations}",
  lat_tab,
  "\\end{table}"
)
cat(paste(latex_tab, collapse = "\n"))
```

``` {r RegTable, results="asis"}
tab <- prepare_regression_table(
  smp, rep("laudit_fees", 4), 
  idvs = list(
    c("big4", "lassets"),  
    c("big4", "lassets", "lrevenues", "lmarket_cap"),  
    c("big4", "lassets"),  
    c("big4", "lassets", "lrevenues", "lmarket_cap")
  ),
  feffects = list("", "", c("entity_map_fkey", "year"), c("entity_map_fkey", "year")),
  clusters = list("", "", c("entity_map_fkey", "year"), c("entity_map_fkey", "year")),
  format = "latex"
)$table

tab[10] <- paste(
  " & \\multicolumn{4}{c}{\\textit{Dependent variable: ", var_labels[1], "}} \\\\"
)
esc_var_names <- str_replace_all(var_names, fixed ("_"), "\\_")
reg_names <- tibble(
  var_name = esc_var_names[c(5, 2:4)],
  label = var_labels[c(5, 2:4)]
)
for (i in seq(15, 24, by = 3)) {
  pos <- (i-12)/3
  tab[i] <- str_replace(
    tab[i], fixed(reg_names$var_name[pos]), reg_names$label[pos]
  )
}

tab[32:33] <- str_replace_all(tab[32:33], fixed("entity\\_map\\_fkey"), "Client")
tab[32:33] <- str_replace_all(tab[32:33], fixed("year"), "Year")
tab <- tab[c(9, 10, 13:36, 38)]
tab[1] <- toprule
tab[27] <- bottomrule


latex_tab <- c(
  "\\begin{table}[!t]",  
  "\\caption{\\label{tab:reg}Audit Fee Premium Regressions}",
  "\\centering",
  "\\begin{threeparttable}",
  "\\begin{tabular}{lcccc}",
  tab,
  "\\end{tabular}",
  "\\begin{tablenotes}[flushleft]",
  "\\item",
  "Notes: This table presents the results of four OLS regressions regressing", 
  "audit fees on various sets of covariates.",
  "The sample and all variables are as defined in Table 1.",
  "Standard errors are presented in parentheses below the coefficients.",
  "$^{*}$/$^{**}$/$^{***}$ indicate two-sided significance levels below",
  "10/5/1 \\%, respectively.",
  "\\end{tablenotes}",
  "\\end{threeparttable}",
  "\\end{table}"
)
cat(paste(latex_tab, collapse = "\n"))

message("done!")
```


